<%@ Page Title="" Language="C#" MasterPageFile="~/Default.master" AutoEventWireup="true" CodeFile="beerfestival.aspx.cs" Inherits="clubs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
 <div id="body">
 <div class="fullwidth">
    <div>
<p style="text-align: center; margin: 0pt;"><span style="font-family: Arial;"><strong><span style="font-size: medium;">History of the </span></strong></span><span style="font-family: Arial;"><strong><span style="font-size: medium;">Duloe </span></strong></span><span style="font-family: Arial;"><strong><span style="font-size: medium;">Beer Festival</span></strong></span><span style="font-family: Arial;"><strong><span style="font-size: medium;"> and </span></strong></span><span style="font-family: Arial;"><strong><span style="font-size: medium;">the </span></strong></span><span style="font-family: Arial;"><strong><span style="font-size: medium;">Duloe Recreation Ground Association</span></strong></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">The Parish Council purchased the Recreation Ground with grants from the Environmental Trust, and since then the Association has been raising funds and applying for grants to build the Club House and buy sports equipment for the people of the village.&nbsp; Two large grants have been very kindly given by SITA and Viridor &ndash; totalling &pound;50,000. The Association is now at a very exciting stage in the development as all the plans have been approved and the timber framed building has been ordered &ndash; work is due to start at anytime!</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">The first Duloe Beer Festival took place in November 2006 and raised &pound;500.&nbsp; In 2</span></span><span style="font-family: Arial;"><span style="font-size: small;">007 the figure doubled to </span></span><span style="font-family: Arial;"><span style="font-size: small;">&pound;1000.</span></span><span style="font-family: Arial;"><span style="font-size: small;">&nbsp; </span></span><span style="font-family: Arial;"><span style="font-size: small;">The third Beer Festival took place in September 200</span></span><span style="font-family: Arial;"><span style="font-size: small;">8 and raised a fantastic &pound;1,760 and last year the amount rose to an amazing &pound;2000!</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">The Association are holding their </span></span><span style="font-family: Arial;"><span style="font-size: small;">newly named - in honour of the contribution made by Cornish Orchards to support the festivals - </span></span><span style="font-family: Arial;"><span style="font-size: small;">5</span></span><span style="font-family: Arial;"><span style="font-size: small;">th</span></span><span style="font-family: Arial;"><span style="font-size: small;"> annual Ale and Cider Festival on Saturday, 18</span></span><span style="font-family: Arial;"><span style="font-size: small;">th</span></span><span style="font-family: Arial;"><span style="font-size: small;"> September 2010, with t</span></span><span style="font-family: Arial;"><span style="font-size: small;">he proceeds </span></span><span style="font-family: Arial;"><span style="font-size: small;">be</span></span><span style="font-family: Arial;"><span style="font-size: small;">ing</span></span><span style="font-family: Arial;"><span style="font-size: small;"> put towards the de</span></span><span style="font-family: Arial;"><span style="font-size: small;">velopment and maintenance of the</span></span><span style="font-family: Arial;"><span style="font-size: small;"> village recreation ground and to purchase further equipment.</span></span><span style="font-family: Arial;"><span style="font-size: small;">&nbsp; </span></span><span style="font-family: Arial;"><span style="font-size: small;">Our beer festivals have been a great success for all concerned to date and, with the help everyone who attends and the </span></span><span style="font-family: Arial;"><span style="font-size: small;">sponsors;</span></span><span style="font-family: Arial;"><span style="font-size: small;"> we hope that this will continue.&nbsp; </span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">Want to get involved with the work</span></span><span style="font-family: Arial;"><span style="font-size: small;"> of the Duloe Recreation Ground</span></span><span style="font-family: Arial;"><span style="font-size: small;">?</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">Interested in sponsoring a barrel at the </span></span><span style="font-family: Arial;"><span style="font-size: small;">Ale and Cider Festival in September?</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">Fancy getting involved wit</span></span><span style="font-family: Arial;"><span style="font-size: small;">h the building of the pavilion?</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">If you have any questions or would like to discuss other ways you can support our endeavours, please do not hesitate to contact </span></span><span style="font-family: Arial;"><span style="font-size: small;">the Association </span></span><span style="font-family: Arial;"><span style="font-size: small;">via </span></span><a href="mailto:Massey1966@hotmail.co.uk"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">Massey1966@hotmail.co.uk</span></span></span></a></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><strong><span style="font-size: medium;">Duloe Beer Festival 2009 </span></strong></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">All the staff from the 2009 </span></span><span style="font-family: Arial;"><span style="font-size: small;">Beer Festival and members of the Duloe Recreation Ground Association would like to say a huge thank you to the follow people who s</span></span><span style="font-family: Arial;"><span style="font-size: small;">ponsored and supported the </span></span><span style="font-family: Arial;"><span style="font-size: small;">Festival</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">List of Sponsors</span></span></p>
<p style="text-align: justify; margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Cornish Orchards Cider</span></span> <a href="http://www.cornishorchards.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.cornishor</span></span></span><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">c</span></span></span><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">hards.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Minerva (SW) Ltd.&nbsp; Civil Engineers.&nbsp; 01503 240970</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Talisman Fishing (Looe) Ltd</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Radio Tactics Ltd. </span></span><a href="http://www.radio-tactics.com/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.radio-tactics.com</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Peake (GB) Limited.&nbsp; </span></span><a href="http://www.peake-gb.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.pea</span></span></span><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">k</span></span></span><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">e-gb.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">PC Kernow.&nbsp; Computer services for home and business&nbsp; </span></span><a href="http://www.pckernow.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.pckernow.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Treleaven&rsquo;s Luxury Cornish Ice Cream.&nbsp; </span></span><a href="http://www.treleavens.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.treleavens.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Sue and John Duffy</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Neil Tucker Electrical Ltd.&nbsp; 01579 346489</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Wanless PK Ltd, Building Contractors.&nbsp; </span></span><a href="http://www.wanless-pk.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.wanless-pk.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">220 Solutions Ltd.&nbsp; PC support services and web design.&nbsp; </span></span><a href="http://www.220solutions.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.220solutions.co.uk</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Phil Seeva and John Sayles</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">John &amp; Lizzie Ridout, Penbugle Farm</span></span><span style="font-family: Arial;"><span style="font-size: small;">, Duloe</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Hedley Stephens</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Waverley</span></span><span style="font-family: Arial;"><span style="font-size: small;"> TBS.&nbsp; Independent Drinks Wholesaler.&nbsp; </span></span><a href="http://www.waverleytbs.co.uk/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.waverleytbs.co.uk</span></span></span></a><span style="font-family: Arial;"><span style="font-size: small;">&nbsp; </span></span></p>
<p style="margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">List of Supporters</span></span></p>
<p style="margin: 0pt;"><span style="font-family: Arial;"><span style="font-size: small;">&nbsp;</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Cornish Orchards</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Swifty at the Barley Sheaf, Liskeard</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Simon Terry at Continental Fruits Ltd &ndash; fabulous nuts!</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Skinners Brewery, </span></span><span style="font-family: Arial;"><span style="font-size: small;">Truro</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">The Marquee Bar and amazing catering staff &ndash; best chips in a cone.</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Tony Barrett - fantastic organic sausages</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Pat Catterall &ndash; delicious pasties.</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Nigel Charlton and </span></span><a href="http://www.duloeonline.com/"><span style="font-family: Arial; color: #0000ff;"><span style="text-decoration: underline;"><span style="font-size: small;">www.duloeonline.com</span></span></span></a></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Gerald and Mark Stevens</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">The Hayloft Restaurant</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">John Sayles for the beautifully painted trestles</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Jo O&rsquo;Keefe</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">Morrisons Supermarket</span></span></p>
<p style="margin: 0pt 0pt 0pt 18pt;"><span style="font-family: Wingdings;"><span style="font-size: small;">v</span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-family: Arial;"><span style="font-size: small;">The Massey gang, John Geach &amp; Rebecca Catterall for the burgers</span></span></p>
<p style="margin: 0pt 0pt 10pt;"><span style="font-family: Arial;"><span style="font-size: small;">&hellip;and last but by no means least, massive thanks goes to everyone who volunteered their time to work at the Beer Festival</span></span><span style="font-family: Arial;"><span style="font-size: small;"> &ndash; without you it would not have been such a success.&nbsp; Thanks to all.</span></span></p>
</div>
<p>&nbsp;</p>
        </div>
     
        
      
 </asp:Content>

